### ISSUE TITLE
404 Error When Accessing SubDirs Directly

### ISSUE THREAD

**Issue by rossenburgg** [StanleySweet/replay-pallas-api#5] opened 2024-02-06 07:22 UTC
When attempting to access subdirectories directly on the http://replay-pallas.wildfiregames.ovh website, such as http://replay-pallas.wildfiregames.ovh/Home, a 404 error is returned. Even tho accessing the site at the root URL works fine which redirects to /Home, looks like a routing issue

**Steps to reproduce**
1. Go to http://replay-pallas.wildfiregames.ovh/Home
2. Observe the 404 error page. ( same applies to all existing subdirs)

**Expected Behavior:**
Accessing subdirectories directly should display the corresponding page without any errors.

**Comment by StanleySweet** [comment] 2024-02-06 07:42
I think the proble might be the usage of http instead of https I might have fixed one but not the other

Stanislas Dolcini
________________________________
From: Defc0n ***@***.***>
Sent: Tuesday, February 6, 2024 4:22:53 PM
To: StanleySweet/replay-pallas-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StanleySweet/replay-pallas-api] 404 Error When Accessing SubDirs Directly (Issue #5)


When attempting to access subdirectories directly on the http://replay-pallas.wildfiregames.ovh website, such as http://replay-pallas.wildfiregames.ovh/Home, a 404 error is returned. Even tho accessing the site at the root URL works fine which redirects to /Home, looks like a routing issue

Steps to reproduce

  1.  Go to http://replay-pallas.wildfiregames.ovh/Home
  2.  Observe the 404 error page. ( same applies to all existing subdirs)

Expected Behavior:
Accessing subdirectories directly should display the corresponding page without any errors.

**Comment by StanleySweet** [comment] 2024-02-06 12:42
Should be fixed now for the main site.

**Closed as completed by StanleySweet** 2024-02-06 12:42 UTC
